apiVersion: "agones.dev/v1"
kind: GameServer
metadata:
  # generate a unique name
  # will need to be created with `kubectl create`
  generateName: deadfish-server-
spec:
  ports:
    - name: default
      portPolicy: Dynamic
      containerPort: 63987
      protocol: TCP
  template:
    spec:
      containers:
      - name: deadfish-server
        image: deadfish-server:latest
        imagePullPolicy: Never
